### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chrma-coder** [RealCyGuy/modmail-plugins#35]
**Describe the bug**
I cannot set the emojis from the Suggest plugin.  When I typed -setemojis, it works, but here's the problem.  Let's look at the code below.

**To Reproduce**

You have this code from lines 260-278.
@commands.command()
    @checks.has_permissions(PermissionLevel.ADMIN)
    async def setemojis(self, ctx, *emojis: discord.Emoji):
        """
        Set emojis to react to each suggestion with.
        **Usage**:
        [p]setemojis \N{WHITE HEAVY CHECK MARK} \N{CROSS MARK}
        [p]se (custom emojis)
        """
        await self.coll.find_one_and_update(
            {"_id": "config"},
            {"$set": {"reaction-emojis": {"emojis": [i.id for i in emojis]}}},
            upsert=True,
        )
        embed = discord.Embed(title=f"Set emojis.", color=0x4DFF73)
        embed.set_author(name="Success!")
        embed.set_footer(text="Task succeeded successfully.")
        await ctx.send(embed=embed)

**Expected behavior**
It shows the emoji is set to no emojis.  When I typed something like :white_check_mark:, :negative_squared_cross_mark:, :thumbsup:, or :thumbsdown:, it would not be able to find the emoji when it does show the emoji on Discord.  What you wanted to do in this code was to make sure that the bot can react to the emojis when set a specific emoji after a person suggests something, is that correct?

**Screenshots**
Below is a screenshot that I would like for you to see.
![Support Suggest](https://user-images.githubusercontent.com/62094974/148272334-ab6c0b24-05fb-4918-a22f-3019a9e88b74.png)

**Comment by RealCyGuy** [comment]
Yeah default discord emojis don't work, only custom ones.
