### ISSUE TITLE
Suggest plugin approve and deny commands not working

### ISSUE THREAD

**Issue by Blackcluemodmail** [RealCyGuy/modmail-plugins#36]
**Describe the bug**

In suggest plugin, approve and deny commands are not working.  

**Screenshots**
![Screenshot_2022-04-04-18-40-15-57](https://user-images.githubusercontent.com/91614979/161551131-f19281b3-7380-4b0a-82ef-72c4ca52695f.jpg)
![Screenshot_2022-04-04-18-40-35-43](https://user-images.githubusercontent.com/91614979/161551139-37ff1820-cae9-4712-8712-e6a5571333a2.jpg)
![Screenshot_2022-04-04-18-40-46-54](https://user-images.githubusercontent.com/91614979/161551143-3559a88b-3de4-46a6-bb36-1cd7357ea13f.jpg)

**Additional context**
I have checked the permissions twice.

**Comment by RealCyGuy** [comment]
Does this issue still exist?
